name: SignOut

on:
  schedule:
    # UTC+8 9~17 -> UTC+0 1~9, run every day.
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  run-signout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run signout.py
        run: python ./code/signout.py
        env: 
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          otpauth: ${{ secrets.otpauth }}
